export default {
    fobCurrency: {},
    fobPrice: {},
    refFobPrice:{},
    fobPort: {},
    exwPrice: {},
    exwCurrency: {},
    cifPrice:{},
    refCifPrice:{},
    cifCurrency:{},
    cifArea:{},
    dduPrice:{},
    refDduPrice:{},
    dduCurrency:{},
    dduArea:{},
}