export default {
    id:{
        _hide:true
    },
    skuId:{
        _hide:true
    },
    customerCreate:{
        _hide:true
    },
    categoryId:{
        _hide:true
    },
    bookmarkId:{
        _hide:true
    },
    pictures: {
        _image:true,
        key:'pictures',
        _fixed:'left',
        _sort:false
    },
    code:{
        _fixed:'left'
    },
    customerSkuCode:{},
    supplierAbbr:{
        mustShowColumn:true,
        _sort:true
    },
    categoryName:{
        key:"categoryName",
        _sort:false
    },
    nameEn:{},
    descEn:{
        _sort:false
    },
    unit:{},

    fobCurrency:{},
    fobPrice:{},
    refFobPrice:{
        _sort:false
    },
    exwCurrency:{},
    exwPrice:{},
    materialEn:{},
    minOrderQty:{},
    deliveryDates:{},
    outerCartonQty:{},
    methodPkgEn:{
        _sort:false
    },
    innerCartonQty:{},
    innerCartonMethodEn:{
        _sort:false
    },
    availableQty:{},
    skuSaleStatus: {
        key:'status'
    },
    readilyAvailable:{},
    noneSellCountry:{},
    outerCartonNetWeight:{},
    outerCartonRoughWeight:{},
    outerCartonVolume:{},
    nameCustomer:{},
    descCustomer:{
        _sort:false
    },
    supplierName:{},
    supplierCode:{},
    formation:{
        _sort:false
    },
    oemQty:{
        mustShowColumn:true,
        _sort:true
    },
    colourEn:{},
    barcode:{
        _sort:false
    },
    applicableAge:{},
    expireDates:{},
    expireUnit:{},
    designs:{
        _upload:{
            readonly:true
        },
        mustShowColumn:true,
    },
    notes:{
        mustShowColumn:true,
        _upload:{
            readonly:true
        }
    },
    fobPort:{
        _sort:false
    },
    cifPrice:{},
    refCifPrice:{
        _sort:false
    },
    cifCurrency:{},
    cifArea:{
        _sort:false
    },
    dduPrice:{},
    refDduPrice:{
        _sort:false
    },
    dduCurrency:{},
    dduArea:{
        _sort:false
    },
    taxRefundRate:{},
    customsCode:{},
    customsNameEn:{},
    tradeMarkEn:{},
    commodityInspectionEn:{},
    origin:{},
    brand:{
        _sort:false
    },
    brandRemark:{
        _sort:false
    },
    brandRelated:{
        _sort:false
    },
    certificat:{
        _sort:false
    },
    unitWeight:{
        _sort:false
    },
    unitLength:{
        _sort:false
    },
    unitVolume:{
        _sort:false
    },
    length:{},
    width:{},
    height:{},
    netWeight:{},
    volume:{},
    innerCartonLength:{},
    innerCartonWidth:{},
    innerCartonHeight:{},
    innerCartonWeightNet:{},
    innerCartonRoughWeight:{},
    innerCartonVolume:{},
    innerCartonDesc:{
        _sort:false
    },
    outerCartonDesc:{
        _sort:false
    },
    innerCartonOuterNum:{},
    outerCartonLength:{},
    outerCartonWidth:{},
    outerCartonHeight:{},
    outerCartonMethodEn:{
        _sort:false
    },
    oem:{},
    gp20SkuQty:{},
    gp40SkuQty:{},
    hq40SkuQty:{},
    tryDimension:{},
    skuQtyPerTray:{},
    specialTransportRequire:{
        _sort:false
    },
    mainSaleCountry:{
        _sort:false
    },
    mainSaleArea:{
        _sort:false
    },
    qualityStander:{
        _sort:false
    },
    yearListed:{},
    useDisplayBox:{},
    displayBoxQty:{},
    lengthWidthHeight:{},
    otherPackInfoEn:{
        _sort:false
    },
    adjustPackage:{},
}
