export default {
    id:{
        _hide:true
    },
    supplierId:{
        _hide:true
    },
    paymentMethod:{
        _hide:true
    },
    departureCountry:{
        _hide:true
    },
    destinationCountry:{
        _hide:true
    },
    orderNo:{
        _hide:true
    },
    inquiryNo:{},
    quotationNo:{},
    inquiryStatus:{
        key:'status'
    },
    supplierName:{},
    skuQty:{},
    currency:{},
    incoterm:{},
    departurePort:{},
    destinationPort:{},
    remark:{},
}