export default {
    id:{
        _hide:true
    },
    inboundNoCn:{
        key:'inboundNo'
    },
    inboundDate:{},
    warehouseNo:{},
    warehouseName:{},
    purchaser:{
        key:'purchaser'
    },
    storageType:{},
    skuTotalQty:{},
    remark:{},
    operator:{
        key:'updateName'
    },
    updateDt:{},
    createDt:{
        key:'entryDt'
    },
    carrier:{},
    carrierPhone:{},
    skuTotalVolume:{},
    skuTotalNetWeight:{},
    skuTotalGrossWeight:{}

}