export default {
    inboundNo:{
        key:'inboundNo',
        belong:'basicInfo',
        showType:'input',
        disabled:true
    },
    inboundDate:{
        key:'inboundDate',
        belong:'basicInfo',
        showType:'date'
    },
    warehouseNo:{
        key:'warehouseNo',
        belong:'basicInfo',
        showType:'input',
    },
    warehouseName:{
        key:'warehouseName',
        belong:'basicInfo',
        showType:'input',
    },
    inboundTypeDictCode:{
        key:'inboundTypeDictCode',
        belong:'basicInfo',
        showType:'select',
        options:[
            {
                label:'采购入库',
                value:'1'
            },
            {
                label:'验货入库',
                value:'2'
            },
        ]
    },
    warehouseManager:{
        key:'warehouseManager',
        belong:'basicInfo',
        showType:'input',
    },
    purchaser:{
        key:'purchaser',
        belong:'basicInfo',
        showType:'input',
    },
    carrier:{
        key:'carrier',
        belong:'basicInfo',
        showType:'input',
    },
    carrierPhone:{
        key:'carrierPhone',
        belong:'basicInfo',
        showType:'input',
    },
    timeZone:{
        key:'timeZone',
        belong:'basicInfo',
        showType:'input',
    },
    remark:{
        key:'remark',
        belong:'basicInfo',
        showType:'textarea',
        fullLine:true
    },
    attachment:{
        key:'attachment',
        belong:'basicInfo',
        showType:'textarea',
        fullLine:true
    }
}