export default {
    skuBarCode:{
        key:'skuBarCode',
    },
    skuCode:{
        key:'skuCode',
    },
    skuNameCn:{
        key:'skuNameCn',
    },
    skuNameCustomer:{
        key:'skuNameCustomer',
    },
    skuNameEn:{
        key:'skuNameEn',
    },
    skuMaterialCn:{
        key:'skuMaterialCn',
    },
    skuMaterialEn:{
        key:'skuMaterialEn'
    },
    factorySkuCode:{
        key:'factorySkuCode',
    },
    customerSkuCode:{
        key:'customerSkuCode'
    },
    skuUnitDictCode:{
        key:'skuUnitDictCode',
    },
    orderSkuQty:{
        key:'orderSkuQty',
    },
    inboundSkuTotalQty:{
        key:'inboundSkuTotalQty',
    },
    inboundOutCartonTotalQty:{
        key:'inboundOutCartonTotalQty'
    },
    inboundSkuTotalVolume:{
        key:'inboundSkuTotalVolume'
    },
    inboundSkuTotalNetWeight:{
        key:'inboundSkuTotalNetWeight',
    },
    inboundSkuTotalGrossWeight:{
        key:'inboundSkuTotalGrossWeight'
    },
    outerCartonSkuQty:{
        key:'outerCartonSkuQty'
    },
    outerCartonVolume:{
        key:'outerCartonVolume'
    },
    outerCartonGrossWeight:{
        key:'outerCartonGrossWeight',
    },
    outerCartonNetWeight:{
        key:'outerCartonNetWeight'
    },
    unqualifiedType:{
        key:'unqualifiedType'
    },
    packingMethodCn:{
        key:'packingMethodCn'
    },
    innerCartonPackingMethodCn:{
        key:'innerCartonPackingMethodCn'
    },
    skuDescEn:{
        key:'skuDescEn'
    },
    skuDescCn:{
        key:'skuDescCn'
    },
    skuDescCustomer:{
        key:'skuDescCustomer'
    },
    skuLength:{
        key:'skuLength'
    },
    skuWidth:{
        key:'skuWidth'
    },
    skuHeight:{
        key:'skuHeight'
    },
    skuNetWeight:{
        key:'skuNetWeight'
    },
    innerCartonLength:{
        key:'innerCartonLength'
    },
    innerCartonWidth:{
        key:'innerCartonWidth'
    },
    innerCartonHeight:{
        key:'innerCartonHeight'
    },
    innerCartonNetWeight:{
        key:'innerCartonNetWeight'
    },
    innerCartonGrossWeight:{
        key:'innerCartonGrossWeight'
    },
    skuBrand:{
        key:'skuBrand'
    },
    innerCartonVolume:{
        key:'innerCartonVolume'
    },
    skuLabel:{
        key:'skuLabel'
    },
    orderNo:{
        key:'orderNo'
    },
    customerOrderNo:{
        key:'customerOrderNo'
    },
    customerNo:{
        key:'customerNo'
    },
    customerName:{
        key:'customerName'
    },
    supplierName:{
        key:"supplierName"
    },
    supplierNo:{
        key:'supplierNo'
    },
    supplierOrderNo:{
        key:'supplierOrderNo'
    },
}