export default {
    outboundNo:{
        key:'outboundNo',
        belong:'basicInfo',
        showType:'input',
        disabled:true
    },
    shipmentInvoiceNo:{
        key:'shipmentInvoiceNo',
        belong:'basicInfo',
        showType:'input'
    },
    outboundTypeDictCode:{
        key:'outboundTypeDictCode',
        belong:'basicInfo',
        showType:'select',
        options:[
            {
                label:'销售出库',
                value:1
            },
            {
                label:'转库',
                value:2
            },
        ],
    },
    outboundDate:{
        key:'outboundDate',
        belong:'basicInfo',
        showType:'date',
    },
    outboundOperator:{
        key:'outboundOperator',
        belong:'basicInfo',
        showType:'input',
    },
    outboundSkuTotalQty:{
        key:'outboundSkuTotalQty',
        belong:'basicInfo',
        showType:'number',
    },
    timeZone:{
        key:'timeZone',
        belong:'basicInfo',
        showType:'timeZone',
    },
    attachment:{
        key:'attachment',
        belong:'basicInfo',
        showType:'textarea',
    },
    remark:{
        key:'remark',
        belong:'basicInfo',
        showType:'textarea',
        fullLine:true
    },

}