export default {
    skuCode:{
        key:'skuCode',
    },
    skuNameCn:{
        key:'skuNameCn',
    },
    skuNameEn:{
        key:'skuNameEn',
    },
    customerSkuCode:{
        key:'customerSkuCode',
    },
    factorySkuCode:{
        key:'factorySkuCode',
    },
    skuMaterialCn:{
        key:'skuMaterialCn',
    },
    skuMaterialEn:{
        key:'skuMaterialEn',
    },
    skuUnitDictCode:{
        key:'skuUnitDictCode',
        showType:'select',
        options:[
            {
                label:'kg',
                value:1
            },
            {
                label:'g',
                value:2
            }
        ]
    },
    outboundSkuTotalQty:{
        key:'outboundSkuTotalQty',
        showType:'number',
        computed:true
    },
    outboundOutCartonTotalQty:{
        key:'outboundOutCartonTotalQty',        //需要传的参数
        showType:'number'
    },
    outboundSkuTotalVolume:{
        key:'outboundSkuTotalVolume',
        showType:'number',
        computed:true
    },
    outboundSkuTotalNetWeight:{
        key:'outboundSkuTotalNetWeight',
        showType:'number',
        computed:true
    },
    outboundSkuTotalGrossWeight:{
        key:'outboundSkuTotalGrossWeight',
        showType:'number',
        computed:true
    },
    outerCartonSkuQty:{
        key:'outerCartonSkuQty',
        showType:'number',
    },
    outerCartonVolume:{
        key:'outerCartonVolume',
        showType:'number',
    },
    outerCartonGrossWeight:{
        key:'outerCartonGrossWeight',
        showType:'number',
    },
    outerCartonNetWeight:{
        key:'outerCartonNetWeight',
        showType:'number',
    },
    //入库日期
    //仓储天数
    inventorySkuPrice:{        //需要传的参数
        key:'inventorySkuPrice',
        showType:'number',
    },
    inventoryServiceFee:{        //需要传的参数
        key:'inventoryServiceFee',
        showType:'number',
    },
    inboundNo:{
        key:'inboundNo',
    },
    skuBarCode:{
        key:'skuBarCode'
    },
    skuNameCustomer:{
        key:'skuNameCustomer'
    },
    skuDescEn:{
        key:'skuDescEn',
    },
    skuDescCn:{
        key:'skuDescCn',
    },
    skuDescCustomer:{
        key:'skuDescCustomer',
    },
    orderNo:{
        key:'orderNo',
    },
    //仓库编号
    //仓库名称
    skuLabel:{
        key:'skuLabel',
    },
}