export default {
    id:{
        _hide:true,
    },
    skuId:{
        _hide:true
    },
    skuPics:{
        _image:true,
        _sort:false
    },
    skuInventoryStatusDictCode:{},
    skuQcStatusDictCode:{},
    orderNo:{},
    skuCode:{},
    customerSkuCode:{},
    supplierAbbr:{},
    skuNameEn:{},
    outboundOutCartonTotalQty:{},
    inventoryOutCartonQty:{},
    inventorySkuQty:{},
    inventorySkuVolume:{},
    inventorySkuGrossWeight:{},
    inventorySkuNetWeight:{},


    inboundNo:{},
    inboundDate:{},
    // customerNo:{},
    // warehouseNo:{},
    // warehouseName:{},
    orderSkuQty:{},
    skuBarCode:{},
    // factorySkuCode:{},
    skuDescEn:{},
    skuUnitDictCode:{},
    inboundOutCartonTotalQty:{},
    inboundSkuTotalQty:{},
    outboundSkuTotalQty:{},
    outerCartonSkuQty:{},
    outerCartonNetWeight:{},
    outerCartonGrossWeight:{},
    outerCartonVolume:{},
    // skuLabel:{},
    // skuLength:{},
    // skuWidth:{},
    // skuHeight:{},
    skuNetWeight:{},
    // innerCartonLength:{},
    // innerCartonWidth:{},
    // innerCartonHeight:{},
    // innerCartonNetWeight:{},
    // innerCartonGrossWeight:{},
    // innerCartonVolume:{},
    skuBrand:{},
    // skuNameCn:{},
}